# Establecer la imagen base
FROM node:14 as build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias del proyecto
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Construir la aplicación para producción
RUN npm run build

# Iniciar una nueva etapa de construcción
FROM nginx:1.19.0-alpine as production

# Copiar los archivos de construcción de la etapa anterior
COPY --from=build /app/build /usr/share/nginx/html

# Exponer el puerto 80 para el servidor nginx
EXPOSE 80

# Iniciar el servidor nginx
CMD ["nginx", "-g", "daemon off;"]